version: '3'
services:
  zookeeper:
    image: "confluentinc/cp-zookeeper:latest"
    restart: always
    network_mode: host
    ports:
      - "22181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: "confluentinc/cp-kafka:latest"
    depends_on:
      - zookeeper
    restart: always
    network_mode: host
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 1
      KAFKA_BROKER_ID: 1

  kafka-client:
    image: "confluentinc/cp-kafka:latest"
    container_name: kafka-client
    network_mode: host
    command: [ "/bin/bash", "-c", "sleep infinity" ]
    volumes:
      - ./kafka-playground/ssl/security:/etc/kafka/secrets
      - ./kafka-playground/ssl/client:/etc/kafka/client