kafkaSelector:
  type: file
  path: gateway-core/config/kafka.config
hostPortConfiguration:
  gatewayBindHost: 0.0.0.0
  gatewayHost: localhost
  portRange: 6969:6975
authenticationConfig:
  authenticatorType: SSL
  sslConfig:
    updateContextIntervalMinutes: 5
    keyStore:
      keyStorePath: gateway-core/config/kafka.gateway.keystore.jks
      keyStorePassword: confluent
      keyPassword: confluent
      keyStoreType: pkcs12
      updateIntervalMsecs: 60000
    trustStore:
      trustStorePath: gateway-core/config/kafka.gateway.truststore.jks
      trustStorePassword: confluent
      keyPassword: confluent
      trustStoreType: jks
      updateIntervalMsecs: 60000
interceptors:
  - name: loggingInterceptor
    pluginClass: io.conduktor.example.loggerinterceptor.LoggerInterceptorPlugin
    timeoutMs: 30000 #optional, default timeoutMs = 30s
    priority: 100
    config:
      - key: "loggingStyle"
        value: "obiWan"